version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: docs/mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Build HTML and PDF versions
formats:
  - htmlzip
  - pdf

# Build all branches and tags
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install any system dependencies if needed
      - pip install --upgrade pip
      # Install documentation dependencies from requirements.txt
      - pip install -r docs/requirements.txt
      # Install the package itself
      - pip install -e .