apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: observability
data:
  policy.rego: |
    package observicia
    
    default allow = true
    
    violation[msg] if {
      input.risk_level == "critical"
      msg := "Critical risk level detected"
    }
    
    violation[msg] if {
      input.token_count > 1000
      msg := "Token limit exceeded"
    }
