service_name: langchain-app
otel_endpoint: null
opa_endpoint: http://opa-server:8181/
policies:
logging:
  file: "app.json"
  telemetry:
    enabled: true
    format: "json"
    redis:
      enabled: true
      host: "localhost"
      port: 6379
      db: 0
      password: null
      key_prefix: "observicia:telemetry:"
      retention_hours: 24
    messages:
    enabled: true
    level: "INFO"
  chat:
    enabled: true
    level: "both"
    file: "langchain-chat.json"