service_name: langchain-app
otel_endpoint: null
opa_endpoint: http://opa-server:8181/
policies:
logging:
  telemetry:
    enabled: true
    format: "sqlite"
    database_path: "telemetry.db"
    enabled: true
    level: "INFO"
  chat:
    enabled: true
    level: "both"
    file: "langchain-chat.json"