site_name: Observicia SDK
site_description: Cloud Native Observability SDK for LLM Applications
site_author: Observicia Team

repo_name: observicia/observicia
repo_url: https://github.com/observicia/observicia
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [sdk]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
